/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author Jader
 */
public class janAbertura extends javax.swing.JFrame {

    /**
     * Creates new form janAbertura
     */
    public janAbertura() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldEdital = new javax.swing.JTextField();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jButtonVoltar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jButtonProximo = new javax.swing.JButton();
        jTabbedPane5 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        horadeinicio = new javax.swing.JLabel();
        textoajudaemissor = new javax.swing.JLabel();
        jTextFieldLocalSessao = new javax.swing.JTextField();
        jTextFieldEmissorPortaria = new javax.swing.JTextField();
        EmissorPortaria = new javax.swing.JLabel();
        LocalSessao = new javax.swing.JLabel();
        textoAjudaLocalSessao = new javax.swing.JLabel();
        PortariaNomeacao = new javax.swing.JLabel();
        textoajudaPortaria = new javax.swing.JLabel();
        jTextPortariaNomeacao = new javax.swing.JTextField();
        jButtonCriarAta = new javax.swing.JButton();
        jTextFieldHoraInstalacao = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLayeredPane3 = new javax.swing.JLayeredPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTablePresencaMemorial = new javax.swing.JTable();
        jButtonCronograma = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLayeredPane4 = new javax.swing.JLayeredPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        jListListaPontos = new javax.swing.JList();
        marqueoscadidatos = new javax.swing.JLabel();
        horadeinicio2 = new javax.swing.JLabel();
        CriarAtaAbertura = new javax.swing.JButton();
        jTextFieldHoraInstalacao1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        jTextFieldEdital.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Abertura");
        setResizable(false);

        jButtonVoltar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icones/back.png"))); // NOI18N
        jButtonVoltar.setMnemonic('v');
        jButtonVoltar.setText("Voltar");
        jButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarActionPerformed(evt);
            }
        });
        jButtonVoltar.setBounds(90, 550, 120, 40);
        jLayeredPane1.add(jButtonVoltar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButtonCancelar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icones/cancel.png"))); // NOI18N
        jButtonCancelar.setMnemonic('c');
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });
        jButtonCancelar.setBounds(210, 550, 120, 40);
        jLayeredPane1.add(jButtonCancelar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButtonProximo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonProximo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icones/next.png"))); // NOI18N
        jButtonProximo.setMnemonic('p');
        jButtonProximo.setText("Próximo");
        jButtonProximo.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButtonProximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonProximoActionPerformed(evt);
            }
        });
        jButtonProximo.setBounds(330, 550, 120, 40);
        jLayeredPane1.add(jButtonProximo, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTabbedPane5.setToolTipText("");

        horadeinicio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        horadeinicio.setText("Hora de início da sessão de instalação da comissão examinadora:");
        horadeinicio.setBounds(60, 50, 420, 17);
        jLayeredPane2.add(horadeinicio, javax.swing.JLayeredPane.DEFAULT_LAYER);

        textoajudaemissor.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        textoajudaemissor.setText("Exemplo: \"Reitora da Universidade Federal do Pampa\" (esta informação constará na ata)");
        textoajudaemissor.setBounds(60, 290, 410, 20);
        jLayeredPane2.add(textoajudaemissor, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTextFieldLocalSessao.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldLocalSessao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldLocalSessaoActionPerformed(evt);
            }
        });
        jTextFieldLocalSessao.setBounds(60, 150, 340, 30);
        jLayeredPane2.add(jTextFieldLocalSessao, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTextFieldEmissorPortaria.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldEmissorPortaria.setBounds(60, 320, 340, 30);
        jLayeredPane2.add(jTextFieldEmissorPortaria, javax.swing.JLayeredPane.DEFAULT_LAYER);

        EmissorPortaria.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        EmissorPortaria.setText("Emissor da portaria de nomeação da banca");
        EmissorPortaria.setBounds(60, 270, 380, 17);
        jLayeredPane2.add(EmissorPortaria, javax.swing.JLayeredPane.DEFAULT_LAYER);

        LocalSessao.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LocalSessao.setText("Local da sessão de instalação da comissão examinadora");
        LocalSessao.setBounds(60, 110, 380, 17);
        jLayeredPane2.add(LocalSessao, javax.swing.JLayeredPane.DEFAULT_LAYER);

        textoAjudaLocalSessao.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        textoAjudaLocalSessao.setText("Exemplo: sala cento e doze do Campus Alegrete");
        textoAjudaLocalSessao.setBounds(60, 130, 220, 13);
        jLayeredPane2.add(textoAjudaLocalSessao, javax.swing.JLayeredPane.DEFAULT_LAYER);

        PortariaNomeacao.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        PortariaNomeacao.setText("Portaria de nomeação da banca");
        PortariaNomeacao.setBounds(60, 190, 380, 17);
        jLayeredPane2.add(PortariaNomeacao, javax.swing.JLayeredPane.DEFAULT_LAYER);

        textoajudaPortaria.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        textoajudaPortaria.setText("Exemplo: 005/2008(esta informação constará na ata)");
        textoajudaPortaria.setBounds(60, 210, 260, 20);
        jLayeredPane2.add(textoajudaPortaria, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTextPortariaNomeacao.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextPortariaNomeacao.setBounds(60, 230, 90, 30);
        jLayeredPane2.add(jTextPortariaNomeacao, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButtonCriarAta.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonCriarAta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icones/ataa.png"))); // NOI18N
        jButtonCriarAta.setText("Cria ata de instalação da comissão examinadora");
        jButtonCriarAta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCriarAtaActionPerformed(evt);
            }
        });
        jButtonCriarAta.setBounds(70, 380, 390, 40);
        jLayeredPane2.add(jButtonCriarAta, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jTextFieldHoraInstalacao.setBounds(60, 70, 70, 30);
        jLayeredPane2.add(jTextFieldHoraInstalacao, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLayeredPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 515, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE)
        );

        jTabbedPane5.addTab("Instalação", jPanel1);

        jTablePresencaMemorial.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Atividade", "Data", "Horário", "Local"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTablePresencaMemorial.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(jTablePresencaMemorial);

        jScrollPane2.setBounds(30, 30, 460, 370);
        jLayeredPane3.add(jScrollPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButtonCronograma.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonCronograma.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icones/cronograma.png"))); // NOI18N
        jButtonCronograma.setText("Cria Cronograma");
        jButtonCronograma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCronogramaActionPerformed(evt);
            }
        });
        jButtonCronograma.setBounds(70, 410, 370, 40);
        jLayeredPane3.add(jButtonCronograma, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 515, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE)
        );

        jTabbedPane5.addTab("Cronograma", jPanel2);

        jScrollPane3.setViewportView(jListListaPontos);

        jScrollPane3.setBounds(50, 40, 430, 310);
        jLayeredPane4.add(jScrollPane3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        marqueoscadidatos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        marqueoscadidatos.setText("Marque os candidatos presentes na sessão de abertura do concurso:");
        marqueoscadidatos.setBounds(50, 10, 450, 17);
        jLayeredPane4.add(marqueoscadidatos, javax.swing.JLayeredPane.DEFAULT_LAYER);

        horadeinicio2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        horadeinicio2.setText("Hora de início da sessão de instalação da comissão examinadora:");
        horadeinicio2.setBounds(50, 360, 420, 17);
        jLayeredPane4.add(horadeinicio2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        CriarAtaAbertura.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CriarAtaAbertura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icones/ataa.png"))); // NOI18N
        CriarAtaAbertura.setText("Criar ata da sessão de abertura do concurso");
        CriarAtaAbertura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CriarAtaAberturaActionPerformed(evt);
            }
        });
        CriarAtaAbertura.setBounds(80, 420, 360, 40);
        jLayeredPane4.add(CriarAtaAbertura, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jTextFieldHoraInstalacao1.setBounds(50, 380, 70, 30);
        jLayeredPane4.add(jTextFieldHoraInstalacao1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 515, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE)
        );

        jTabbedPane5.addTab("Abertura", jPanel3);

        jTabbedPane5.setBounds(0, 50, 520, 500);
        jLayeredPane1.add(jTabbedPane5, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Abertura");
        jLabel1.setBounds(220, 10, 100, 29);
        jLayeredPane1.add(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 518, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 595, Short.MAX_VALUE)
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-536)/2, (screenSize.height-642)/2, 536, 642);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCriarAtaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCriarAtaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCriarAtaActionPerformed

    private void jTextFieldLocalSessaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldLocalSessaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldLocalSessaoActionPerformed

    private void jButtonCronogramaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCronogramaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCronogramaActionPerformed

    private void CriarAtaAberturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CriarAtaAberturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CriarAtaAberturaActionPerformed

    private void jButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarActionPerformed
        // TODO add your handling code here:
        int nextTab = jTabbedPane5.getSelectedIndex() - 1;
        if (nextTab >= 0) {
            jTabbedPane5.setSelectedIndex(nextTab);
        }
    }//GEN-LAST:event_jButtonVoltarActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonProximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProximoActionPerformed

        // TODO add your handling code here:
        int nextTab = jTabbedPane5.getSelectedIndex() + 1;
        if (nextTab < jTabbedPane5.getTabCount()) {
            jTabbedPane5.setSelectedIndex(nextTab);
        }
    }//GEN-LAST:event_jButtonProximoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(janAbertura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(janAbertura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(janAbertura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(janAbertura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new janAbertura().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CriarAtaAbertura;
    private javax.swing.JLabel EmissorPortaria;
    private javax.swing.JLabel LocalSessao;
    private javax.swing.JLabel PortariaNomeacao;
    private javax.swing.JLabel horadeinicio;
    private javax.swing.JLabel horadeinicio2;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonCriarAta;
    private javax.swing.JButton jButtonCronograma;
    private javax.swing.JButton jButtonProximo;
    private javax.swing.JButton jButtonVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JLayeredPane jLayeredPane3;
    private javax.swing.JLayeredPane jLayeredPane4;
    private javax.swing.JList jListListaPontos;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane5;
    private javax.swing.JTable jTablePresencaMemorial;
    private javax.swing.JTextField jTextFieldEdital;
    private javax.swing.JTextField jTextFieldEmissorPortaria;
    private javax.swing.JTextField jTextFieldHoraInstalacao;
    private javax.swing.JTextField jTextFieldHoraInstalacao1;
    private javax.swing.JTextField jTextFieldLocalSessao;
    private javax.swing.JTextField jTextPortariaNomeacao;
    private javax.swing.JLabel marqueoscadidatos;
    private javax.swing.JLabel textoAjudaLocalSessao;
    private javax.swing.JLabel textoajudaPortaria;
    private javax.swing.JLabel textoajudaemissor;
    // End of variables declaration//GEN-END:variables
}
