/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author gattuso
 */
public class janCadBibliografia extends javax.swing.JFrame {

    /**
     * Creates new form janCadBibliografia
     */
    public janCadBibliografia() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        btnSalvar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        titulo = new javax.swing.JLabel();
        autor = new javax.swing.JLabel();
        locaimpressao = new javax.swing.JLabel();
        anopublicacao = new javax.swing.JLabel();
        edicao = new javax.swing.JLabel();
        edtTitulo = new javax.swing.JTextField();
        edtAutor = new javax.swing.JTextField();
        edtEdicao = new javax.swing.JTextField();
        edtLocalImpressao = new javax.swing.JTextField();
        edtAno = new javax.swing.JTextField();
        cadbiblio = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        numpg = new javax.swing.JLabel();
        numexemp = new javax.swing.JLabel();
        edtNumEx = new javax.swing.JTextField();
        edtNumPg = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/util/img/save.png"))); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.setBounds(120, 270, 150, 40);
        jLayeredPane1.add(btnSalvar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/util/img/cancel.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.setBounds(270, 270, 150, 40);
        jLayeredPane1.add(btnCancelar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        titulo.setText("Título:");
        titulo.setBounds(20, 80, 120, 17);
        jLayeredPane1.add(titulo, javax.swing.JLayeredPane.DEFAULT_LAYER);

        autor.setText("Autor:");
        autor.setBounds(20, 110, 47, 17);
        jLayeredPane1.add(autor, javax.swing.JLayeredPane.DEFAULT_LAYER);

        locaimpressao.setText("Local da Impressão:");
        locaimpressao.setBounds(20, 170, 138, 17);
        jLayeredPane1.add(locaimpressao, javax.swing.JLayeredPane.DEFAULT_LAYER);

        anopublicacao.setText("Ano da Publicação:");
        anopublicacao.setBounds(160, 140, 136, 17);
        jLayeredPane1.add(anopublicacao, javax.swing.JLayeredPane.DEFAULT_LAYER);

        edicao.setText("Edição:");
        edicao.setBounds(20, 140, 90, 17);
        jLayeredPane1.add(edicao, javax.swing.JLayeredPane.DEFAULT_LAYER);
        edtTitulo.setBounds(80, 70, 340, 27);
        jLayeredPane1.add(edtTitulo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        edtAutor.setBounds(80, 100, 340, 27);
        jLayeredPane1.add(edtAutor, javax.swing.JLayeredPane.DEFAULT_LAYER);
        edtEdicao.setBounds(80, 130, 70, 27);
        jLayeredPane1.add(edtEdicao, javax.swing.JLayeredPane.DEFAULT_LAYER);
        edtLocalImpressao.setBounds(160, 160, 260, 27);
        jLayeredPane1.add(edtLocalImpressao, javax.swing.JLayeredPane.DEFAULT_LAYER);
        edtAno.setBounds(300, 130, 70, 27);
        jLayeredPane1.add(edtAno, javax.swing.JLayeredPane.DEFAULT_LAYER);

        cadbiblio.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        cadbiblio.setText("Cadastro de Bibliografia");
        cadbiblio.setBounds(100, 20, 220, 21);
        jLayeredPane1.add(cadbiblio, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jSeparator1.setBounds(0, 50, 430, 10);
        jLayeredPane1.add(jSeparator1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        numpg.setText("Número de Páginas:");
        numpg.setBounds(20, 200, 142, 17);
        jLayeredPane1.add(numpg, javax.swing.JLayeredPane.DEFAULT_LAYER);

        numexemp.setText("Número de Exemplares:");
        numexemp.setBounds(20, 230, 168, 17);
        jLayeredPane1.add(numexemp, javax.swing.JLayeredPane.DEFAULT_LAYER);
        edtNumEx.setBounds(190, 220, 70, 27);
        jLayeredPane1.add(edtNumEx, javax.swing.JLayeredPane.DEFAULT_LAYER);
        edtNumPg.setBounds(190, 190, 70, 27);
        jLayeredPane1.add(edtNumPg, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(janCadBibliografia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(janCadBibliografia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(janCadBibliografia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(janCadBibliografia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new janCadBibliografia().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel anopublicacao;
    private javax.swing.JLabel autor;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JLabel cadbiblio;
    private javax.swing.JLabel edicao;
    private javax.swing.JTextField edtAno;
    private javax.swing.JTextField edtAutor;
    private javax.swing.JTextField edtEdicao;
    private javax.swing.JTextField edtLocalImpressao;
    private javax.swing.JTextField edtNumEx;
    private javax.swing.JTextField edtNumPg;
    private javax.swing.JTextField edtTitulo;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel locaimpressao;
    private javax.swing.JLabel numexemp;
    private javax.swing.JLabel numpg;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
