package view;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Douglas F. Almeida
 */
public class janNovoConc extends javax.swing.JFrame {

    /**
     * Creates new form janNovoConc
     */
    public janNovoConc() {
        super("Configurações do Concurso");
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel1 = new javax.swing.JLabel();
        btnProximo = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();
        jTabbedPane5 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        jLabel2 = new javax.swing.JLabel();
        ministerio = new javax.swing.JLabel();
        instituicao = new javax.swing.JLabel();
        data = new javax.swing.JLabel();
        jTextFieldMinis = new javax.swing.JTextField();
        edtInstituicao = new javax.swing.JTextField();
        edtEdital = new javax.swing.JTextField();
        edtData = new javax.swing.JTextField();
        campus = new javax.swing.JLabel();
        classe = new javax.swing.JLabel();
        edtCampus = new javax.swing.JTextField();
        edtArea = new javax.swing.JTextField();
        sClasseConcurso = new javax.swing.JComboBox();
        edital = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLayeredPane3 = new javax.swing.JLayeredPane();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        edtPresidente = new javax.swing.JTextField();
        edtOutro = new javax.swing.JTextField();
        sCategoria = new javax.swing.JComboBox();
        sSexo = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        edtExaminador1 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        edtCategoria1 = new javax.swing.JComboBox();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        edtOutro1 = new javax.swing.JTextField();
        sSexo2 = new javax.swing.JComboBox();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        edtExaminador2 = new javax.swing.JTextField();
        sCategoria2 = new javax.swing.JComboBox();
        jLabel19 = new javax.swing.JLabel();
        edtOutro2 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        edtSexo2 = new javax.swing.JComboBox();
        jPanel3 = new javax.swing.JPanel();
        jLayeredPane4 = new javax.swing.JLayeredPane();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        edtNome = new javax.swing.JTextField();
        sSexo3 = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        tCandidatos = new javax.swing.JTable();
        btnExcluir = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnAdicionar = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        edtDataNasc3 = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jPanel4 = new javax.swing.JPanel();
        jCheckBoxProvaEscrita = new javax.swing.JCheckBox();
        jCheckBoxProvaDeTitulos = new javax.swing.JCheckBox();
        jCheckBoxProvaMemorial = new javax.swing.JCheckBox();
        jCheckBoxProvaDidatica = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Configurações do Concurso");
        jLabel1.setBounds(110, 10, 350, 29);
        jLayeredPane1.add(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        btnProximo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnProximo.setText("Próximo");
        btnProximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProximoActionPerformed(evt);
            }
        });
        btnProximo.setBounds(670, 470, 90, 25);
        jLayeredPane1.add(btnProximo, javax.swing.JLayeredPane.DEFAULT_LAYER);

        btnCancelar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        btnCancelar.setBounds(570, 470, 100, 25);
        jLayeredPane1.add(btnCancelar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        btnVoltar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });
        btnVoltar.setBounds(490, 470, 80, 25);
        jLayeredPane1.add(btnVoltar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTabbedPane5.setToolTipText("");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Área:");
        jLabel2.setBounds(290, 110, 50, 17);
        jLayeredPane2.add(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        ministerio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ministerio.setText("Ministério:");
        ministerio.setBounds(10, 50, 70, 17);
        jLayeredPane2.add(ministerio, javax.swing.JLayeredPane.DEFAULT_LAYER);

        instituicao.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        instituicao.setText("Instituíção:");
        instituicao.setBounds(10, 80, 70, 17);
        jLayeredPane2.add(instituicao, javax.swing.JLayeredPane.DEFAULT_LAYER);

        data.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        data.setText("Data de Início:");
        data.setBounds(240, 140, 100, 17);
        jLayeredPane2.add(data, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTextFieldMinis.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldMinis.setBounds(80, 50, 410, 23);
        jLayeredPane2.add(jTextFieldMinis, javax.swing.JLayeredPane.DEFAULT_LAYER);

        edtInstituicao.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        edtInstituicao.setBounds(80, 80, 410, 23);
        jLayeredPane2.add(edtInstituicao, javax.swing.JLayeredPane.DEFAULT_LAYER);

        edtEdital.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        edtEdital.setBounds(80, 140, 150, 23);
        jLayeredPane2.add(edtEdital, javax.swing.JLayeredPane.DEFAULT_LAYER);

        edtData.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        edtData.setBounds(330, 140, 160, 23);
        jLayeredPane2.add(edtData, javax.swing.JLayeredPane.DEFAULT_LAYER);

        campus.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        campus.setText("Campus:");
        campus.setBounds(10, 110, 70, 17);
        jLayeredPane2.add(campus, javax.swing.JLayeredPane.DEFAULT_LAYER);

        classe.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        classe.setText("Classe do Concurso:");
        classe.setBounds(10, 170, 140, 17);
        jLayeredPane2.add(classe, javax.swing.JLayeredPane.DEFAULT_LAYER);

        edtCampus.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        edtCampus.setBounds(80, 110, 200, 23);
        jLayeredPane2.add(edtCampus, javax.swing.JLayeredPane.DEFAULT_LAYER);

        edtArea.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        edtArea.setBounds(330, 110, 160, 23);
        jLayeredPane2.add(edtArea, javax.swing.JLayeredPane.DEFAULT_LAYER);

        sClasseConcurso.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Adjunto", "Assistente", "Auxiliar" }));
        sClasseConcurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sClasseConcursoActionPerformed(evt);
            }
        });
        sClasseConcurso.setBounds(140, 170, 90, 20);
        jLayeredPane2.add(sClasseConcurso, javax.swing.JLayeredPane.DEFAULT_LAYER);

        edital.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        edital.setText("Edital:");
        edital.setBounds(10, 140, 50, 17);
        jLayeredPane2.add(edital, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 765, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 372, Short.MAX_VALUE)
        );

        jTabbedPane5.addTab("Dados Gerais", jPanel1);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Presidente:");
        jLabel9.setBounds(10, 20, 70, 17);
        jLayeredPane3.add(jLabel9, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Sexo:");
        jLabel10.setBounds(330, 20, 50, 17);
        jLayeredPane3.add(jLabel10, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Outro:");
        jLabel11.setBounds(230, 50, 70, 20);
        jLayeredPane3.add(jLabel11, javax.swing.JLayeredPane.DEFAULT_LAYER);

        edtPresidente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        edtPresidente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtPresidenteActionPerformed(evt);
            }
        });
        edtPresidente.setBounds(80, 20, 240, 23);
        jLayeredPane3.add(edtPresidente, javax.swing.JLayeredPane.DEFAULT_LAYER);

        edtOutro.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        edtOutro.setBounds(280, 50, 190, 23);
        jLayeredPane3.add(edtOutro, javax.swing.JLayeredPane.DEFAULT_LAYER);

        sCategoria.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        sCategoria.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Professor Titular", "Professor Associado", "Professor Adjunto", "Outro", " " }));
        sCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sCategoriaActionPerformed(evt);
            }
        });
        sCategoria.setBounds(80, 50, 140, 23);
        jLayeredPane3.add(sCategoria, javax.swing.JLayeredPane.DEFAULT_LAYER);

        sSexo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        sSexo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Masculino", "Feminino", " " }));
        sSexo.setBounds(370, 20, 100, 23);
        jLayeredPane3.add(sSexo, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Categoria:");
        jLabel12.setBounds(10, 50, 70, 20);
        jLayeredPane3.add(jLabel12, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jSeparator1.setBounds(0, 180, 500, 20);
        jLayeredPane3.add(jSeparator1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Examinador:");
        jLabel13.setBounds(10, 110, 90, 17);
        jLayeredPane3.add(jLabel13, javax.swing.JLayeredPane.DEFAULT_LAYER);

        edtExaminador1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        edtExaminador1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtExaminador1ActionPerformed(evt);
            }
        });
        edtExaminador1.setBounds(90, 110, 230, 23);
        jLayeredPane3.add(edtExaminador1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("Categoria:");
        jLabel14.setBounds(10, 140, 70, 20);
        jLayeredPane3.add(jLabel14, javax.swing.JLayeredPane.DEFAULT_LAYER);

        edtCategoria1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        edtCategoria1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Professor Titular", "Professor Associado", "Professor Adjunto", "Outro", " " }));
        edtCategoria1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtCategoria1ActionPerformed(evt);
            }
        });
        edtCategoria1.setBounds(80, 140, 140, 23);
        jLayeredPane3.add(edtCategoria1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText("Outro:");
        jLabel15.setBounds(230, 140, 70, 20);
        jLayeredPane3.add(jLabel15, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setText("Sexo:");
        jLabel16.setBounds(330, 110, 50, 17);
        jLayeredPane3.add(jLabel16, javax.swing.JLayeredPane.DEFAULT_LAYER);

        edtOutro1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        edtOutro1.setBounds(280, 140, 190, 23);
        jLayeredPane3.add(edtOutro1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        sSexo2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        sSexo2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Masculino", "Feminino", " " }));
        sSexo2.setBounds(370, 110, 100, 23);
        jLayeredPane3.add(sSexo2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jSeparator2.setBounds(0, 90, 500, 20);
        jLayeredPane3.add(jSeparator2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setText("Examinador:");
        jLabel17.setBounds(10, 200, 90, 17);
        jLayeredPane3.add(jLabel17, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setText("Categoria:");
        jLabel18.setBounds(10, 230, 70, 20);
        jLayeredPane3.add(jLabel18, javax.swing.JLayeredPane.DEFAULT_LAYER);

        edtExaminador2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        edtExaminador2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtExaminador2ActionPerformed(evt);
            }
        });
        edtExaminador2.setBounds(90, 200, 230, 23);
        jLayeredPane3.add(edtExaminador2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        sCategoria2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        sCategoria2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Professor Titular", "Professor Associado", "Professor Adjunto", "Outro", " " }));
        sCategoria2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sCategoria2ActionPerformed(evt);
            }
        });
        sCategoria2.setBounds(80, 230, 140, 23);
        jLayeredPane3.add(sCategoria2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel19.setText("Outro:");
        jLabel19.setBounds(230, 230, 70, 20);
        jLayeredPane3.add(jLabel19, javax.swing.JLayeredPane.DEFAULT_LAYER);

        edtOutro2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        edtOutro2.setBounds(280, 230, 190, 23);
        jLayeredPane3.add(edtOutro2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel20.setText("Sexo:");
        jLabel20.setBounds(330, 200, 50, 17);
        jLayeredPane3.add(jLabel20, javax.swing.JLayeredPane.DEFAULT_LAYER);

        edtSexo2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        edtSexo2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Masculino", "Feminino", " " }));
        edtSexo2.setBounds(370, 200, 100, 23);
        jLayeredPane3.add(edtSexo2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 765, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 372, Short.MAX_VALUE)
        );

        jTabbedPane5.addTab("Banca Examinador", jPanel2);

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel21.setText("Nome:");
        jLabel21.setBounds(30, 80, 41, 17);
        jLayeredPane4.add(jLabel21, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel22.setText("Sexo:");
        jLabel22.setBounds(280, 80, 36, 17);
        jLayeredPane4.add(jLabel22, javax.swing.JLayeredPane.DEFAULT_LAYER);

        edtNome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        edtNome.setBounds(30, 100, 240, 23);
        jLayeredPane4.add(edtNome, javax.swing.JLayeredPane.DEFAULT_LAYER);

        sSexo3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        sSexo3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Masculino", "Feminino", " " }));
        sSexo3.setBounds(280, 100, 100, 23);
        jLayeredPane4.add(sSexo3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        tCandidatos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tCandidatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Candidatos:"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tCandidatos);
        tCandidatos.getColumnModel().getColumn(0).setResizable(false);

        jScrollPane1.setBounds(420, 100, 320, 190);
        jLayeredPane4.add(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        btnExcluir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.setBounds(280, 260, 100, 25);
        jLayeredPane4.add(btnExcluir, javax.swing.JLayeredPane.DEFAULT_LAYER);

        btnEditar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.setBounds(280, 230, 100, 25);
        jLayeredPane4.add(btnEditar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        btnAdicionar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAdicionar.setText("Adicionar");
        btnAdicionar.setBounds(280, 200, 100, 25);
        jLayeredPane4.add(btnAdicionar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel24.setText("Data de Nascimento:");
        jLabel24.setBounds(30, 130, 140, 17);
        jLayeredPane4.add(jLabel24, javax.swing.JLayeredPane.DEFAULT_LAYER);

        edtDataNasc3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        edtDataNasc3.setBounds(30, 150, 130, 23);
        jLayeredPane4.add(edtDataNasc3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator3.setBounds(400, 70, 10, 260);
        jLayeredPane4.add(jSeparator3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 765, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLayeredPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabbedPane5.addTab("Candidatos", jPanel3);

        jCheckBoxProvaEscrita.setText("Prova Escrita");

        jCheckBoxProvaDeTitulos.setText("Prova de Titulos");

        jCheckBoxProvaMemorial.setText("Prova Memorial");

        jCheckBoxProvaDidatica.setText("Prova Didática");
        jCheckBoxProvaDidatica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxProvaDidaticaActionPerformed(evt);
            }
        });

        jLabel3.setText("Selecione os tipos de provas que fazem parte desse concurso.");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBoxProvaDeTitulos)
                    .addComponent(jCheckBoxProvaMemorial)
                    .addComponent(jCheckBoxProvaDidatica)
                    .addComponent(jCheckBoxProvaEscrita)
                    .addComponent(jLabel3))
                .addContainerGap(456, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jCheckBoxProvaEscrita)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBoxProvaDeTitulos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBoxProvaMemorial)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBoxProvaDidatica)
                .addContainerGap(237, Short.MAX_VALUE))
        );

        jTabbedPane5.addTab("Provas do Concurso", jPanel4);

        jTabbedPane5.setBounds(0, 50, 770, 400);
        jLayeredPane1.add(jTabbedPane5, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 773, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 502, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sClasseConcursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sClasseConcursoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sClasseConcursoActionPerformed

    private void edtPresidenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtPresidenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtPresidenteActionPerformed

    private void sCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sCategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sCategoriaActionPerformed

    private void edtExaminador1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtExaminador1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtExaminador1ActionPerformed

    private void edtCategoria1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtCategoria1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtCategoria1ActionPerformed

    private void edtExaminador2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtExaminador2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtExaminador2ActionPerformed

    private void sCategoria2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sCategoria2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sCategoria2ActionPerformed

    private void btnProximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProximoActionPerformed

        // TODO add your handling code here:
        int nextTab = jTabbedPane5.getSelectedIndex() + 1;
        if (nextTab < jTabbedPane5.getTabCount()) {
            jTabbedPane5.setSelectedIndex(nextTab);
        }

    }//GEN-LAST:event_btnProximoActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        // TODO add your handling code here:
        int nextTab = jTabbedPane5.getSelectedIndex() - 1;
        if (nextTab >= 0) {
            jTabbedPane5.setSelectedIndex(nextTab);
        }
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void jCheckBoxProvaDidaticaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxProvaDidaticaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxProvaDidaticaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(janNovoConc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(janNovoConc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(janNovoConc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(janNovoConc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new janNovoConc().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnProximo;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel campus;
    private javax.swing.JLabel classe;
    private javax.swing.JLabel data;
    private javax.swing.JLabel edital;
    private javax.swing.JTextField edtArea;
    private javax.swing.JTextField edtCampus;
    private javax.swing.JComboBox edtCategoria1;
    private javax.swing.JTextField edtData;
    private javax.swing.JTextField edtDataNasc3;
    private javax.swing.JTextField edtEdital;
    private javax.swing.JTextField edtExaminador1;
    private javax.swing.JTextField edtExaminador2;
    private javax.swing.JTextField edtInstituicao;
    private javax.swing.JTextField edtNome;
    private javax.swing.JTextField edtOutro;
    private javax.swing.JTextField edtOutro1;
    private javax.swing.JTextField edtOutro2;
    private javax.swing.JTextField edtPresidente;
    private javax.swing.JComboBox edtSexo2;
    private javax.swing.JLabel instituicao;
    private javax.swing.JCheckBox jCheckBoxProvaDeTitulos;
    private javax.swing.JCheckBox jCheckBoxProvaDidatica;
    private javax.swing.JCheckBox jCheckBoxProvaEscrita;
    private javax.swing.JCheckBox jCheckBoxProvaMemorial;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JLayeredPane jLayeredPane3;
    private javax.swing.JLayeredPane jLayeredPane4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTabbedPane jTabbedPane5;
    private javax.swing.JTextField jTextFieldMinis;
    private javax.swing.JLabel ministerio;
    private javax.swing.JComboBox sCategoria;
    private javax.swing.JComboBox sCategoria2;
    private javax.swing.JComboBox sClasseConcurso;
    private javax.swing.JComboBox sSexo;
    private javax.swing.JComboBox sSexo2;
    private javax.swing.JComboBox sSexo3;
    private javax.swing.JTable tCandidatos;
    // End of variables declaration//GEN-END:variables
}
