package view;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Douglas F. Almeida
 */
public class janNovoConc extends javax.swing.JFrame {

    /**
     * Creates new form janNovoConc
     */
    public janNovoConc() {
        super("Configurações do Concurso");
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel1 = new javax.swing.JLabel();
        jButtonProximo = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jButtonVoltar = new javax.swing.JButton();
        jTabbedPane5 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        jLabel2 = new javax.swing.JLabel();
        ministerio = new javax.swing.JLabel();
        instituicao = new javax.swing.JLabel();
        data = new javax.swing.JLabel();
        jTextFieldMinisterio = new javax.swing.JTextField();
        jTextFieldInstituicao = new javax.swing.JTextField();
        jTextFieldEdital = new javax.swing.JTextField();
        campus = new javax.swing.JLabel();
        classe = new javax.swing.JLabel();
        jTextFieldCampus = new javax.swing.JTextField();
        jTextFieldArea = new javax.swing.JTextField();
        jComboBoxClasse = new javax.swing.JComboBox();
        edital = new javax.swing.JLabel();
        jDateChooserData = new com.toedter.calendar.JDateChooser();
        jPanel2 = new javax.swing.JPanel();
        jLayeredPane3 = new javax.swing.JLayeredPane();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldPresidente = new javax.swing.JTextField();
        jTextFieldOutro = new javax.swing.JTextField();
        jComboBoxCategoria = new javax.swing.JComboBox();
        jComboBoxSexo = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        jTextFieldExaminador1 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jComboBoxCategoria1 = new javax.swing.JComboBox();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jTextFieldOutro1 = new javax.swing.JTextField();
        jComboBoxSexo2 = new javax.swing.JComboBox();
        jSeparator2 = new javax.swing.JSeparator();
        jTextFieldOutro3 = new javax.swing.JTextField();
        jComboBoxSexo3 = new javax.swing.JComboBox();
        jTextFieldExaminador3 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jComboBoxCategoria3 = new javax.swing.JComboBox();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLayeredPane4 = new javax.swing.JLayeredPane();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jTextFieldNome = new javax.swing.JTextField();
        jComboBoxSexo4 = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        tCandidatos = new javax.swing.JTable();
        jButtonExcluir = new javax.swing.JButton();
        jButtonEditar = new javax.swing.JButton();
        jButtonAdicionar = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jPanel4 = new javax.swing.JPanel();
        jCheckBoxProvaEscrita = new javax.swing.JCheckBox();
        jCheckBoxProvaDeTitulos = new javax.swing.JCheckBox();
        jCheckBoxProvaMemorial = new javax.swing.JCheckBox();
        jCheckBoxProvaDidatica = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Novo Concurso");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Configurações do Concurso");
        jLabel1.setBounds(220, 10, 350, 29);
        jLayeredPane1.add(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButtonProximo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonProximo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icones/next.png"))); // NOI18N
        jButtonProximo.setText("Próximo");
        jButtonProximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonProximoActionPerformed(evt);
            }
        });
        jButtonProximo.setBounds(600, 450, 120, 40);
        jLayeredPane1.add(jButtonProximo, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButtonCancelar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icones/cancel.png"))); // NOI18N
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });
        jButtonCancelar.setBounds(480, 450, 120, 40);
        jLayeredPane1.add(jButtonCancelar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButtonVoltar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icones/back.png"))); // NOI18N
        jButtonVoltar.setText("Voltar");
        jButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarActionPerformed(evt);
            }
        });
        jButtonVoltar.setBounds(360, 450, 120, 40);
        jLayeredPane1.add(jButtonVoltar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTabbedPane5.setToolTipText("");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Área:");
        jLabel2.setBounds(370, 150, 50, 17);
        jLayeredPane2.add(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        ministerio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ministerio.setText("Ministério:");
        ministerio.setBounds(210, 50, 70, 17);
        jLayeredPane2.add(ministerio, javax.swing.JLayeredPane.DEFAULT_LAYER);

        instituicao.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        instituicao.setText("Instituíção:");
        instituicao.setBounds(210, 100, 70, 17);
        jLayeredPane2.add(instituicao, javax.swing.JLayeredPane.DEFAULT_LAYER);

        data.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        data.setText("Data de Início:");
        data.setBounds(370, 200, 100, 17);
        jLayeredPane2.add(data, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTextFieldMinisterio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldMinisterio.setBounds(210, 70, 320, 30);
        jLayeredPane2.add(jTextFieldMinisterio, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTextFieldInstituicao.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldInstituicao.setBounds(210, 120, 320, 30);
        jLayeredPane2.add(jTextFieldInstituicao, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTextFieldEdital.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldEdital.setBounds(210, 220, 150, 30);
        jLayeredPane2.add(jTextFieldEdital, javax.swing.JLayeredPane.DEFAULT_LAYER);

        campus.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        campus.setText("Campus:");
        campus.setBounds(210, 150, 70, 17);
        jLayeredPane2.add(campus, javax.swing.JLayeredPane.DEFAULT_LAYER);

        classe.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        classe.setText("Classe do Concurso:");
        classe.setBounds(210, 250, 140, 17);
        jLayeredPane2.add(classe, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTextFieldCampus.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldCampus.setBounds(210, 170, 150, 30);
        jLayeredPane2.add(jTextFieldCampus, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTextFieldArea.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldArea.setBounds(370, 170, 160, 30);
        jLayeredPane2.add(jTextFieldArea, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jComboBoxClasse.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Adjunto", "Assistente", "Auxiliar" }));
        jComboBoxClasse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxClasseActionPerformed(evt);
            }
        });
        jComboBoxClasse.setBounds(340, 250, 90, 30);
        jLayeredPane2.add(jComboBoxClasse, javax.swing.JLayeredPane.DEFAULT_LAYER);

        edital.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        edital.setText("Edital:");
        edital.setBounds(210, 200, 50, 17);
        jLayeredPane2.add(edital, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDateChooserData.setBounds(370, 220, 160, 30);
        jLayeredPane2.add(jDateChooserData, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 735, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
        );

        jTabbedPane5.addTab("Dados Gerais", jPanel1);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Presidente:");
        jLabel9.setBounds(200, 10, 70, 17);
        jLayeredPane3.add(jLabel9, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Sexo:");
        jLabel10.setBounds(450, 10, 50, 17);
        jLayeredPane3.add(jLabel10, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Outro:");
        jLabel11.setBounds(350, 60, 70, 20);
        jLayeredPane3.add(jLabel11, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTextFieldPresidente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldPresidente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPresidenteActionPerformed(evt);
            }
        });
        jTextFieldPresidente.setBounds(200, 30, 240, 30);
        jLayeredPane3.add(jTextFieldPresidente, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTextFieldOutro.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldOutro.setBounds(350, 80, 200, 30);
        jLayeredPane3.add(jTextFieldOutro, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jComboBoxCategoria.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBoxCategoria.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Professor Titular", "Professor Associado", "Professor Adjunto", "Outro", " " }));
        jComboBoxCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCategoriaActionPerformed(evt);
            }
        });
        jComboBoxCategoria.setBounds(200, 80, 140, 30);
        jLayeredPane3.add(jComboBoxCategoria, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jComboBoxSexo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBoxSexo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Masculino", "Feminino", " " }));
        jComboBoxSexo.setBounds(450, 30, 100, 30);
        jLayeredPane3.add(jComboBoxSexo, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Categoria:");
        jLabel12.setBounds(200, 60, 70, 20);
        jLayeredPane3.add(jLabel12, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jSeparator1.setBounds(0, 240, 730, 10);
        jLayeredPane3.add(jSeparator1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Examinador:");
        jLabel13.setBounds(200, 130, 90, 17);
        jLayeredPane3.add(jLabel13, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTextFieldExaminador1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldExaminador1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldExaminador1ActionPerformed(evt);
            }
        });
        jTextFieldExaminador1.setBounds(200, 150, 240, 30);
        jLayeredPane3.add(jTextFieldExaminador1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("Categoria:");
        jLabel14.setBounds(200, 180, 70, 20);
        jLayeredPane3.add(jLabel14, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jComboBoxCategoria1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBoxCategoria1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Professor Titular", "Professor Associado", "Professor Adjunto", "Outro", " " }));
        jComboBoxCategoria1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCategoria1ActionPerformed(evt);
            }
        });
        jComboBoxCategoria1.setBounds(200, 200, 140, 30);
        jLayeredPane3.add(jComboBoxCategoria1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText("Outro:");
        jLabel15.setBounds(350, 180, 70, 20);
        jLayeredPane3.add(jLabel15, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setText("Sexo:");
        jLabel16.setBounds(450, 130, 50, 17);
        jLayeredPane3.add(jLabel16, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTextFieldOutro1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldOutro1.setBounds(350, 200, 200, 30);
        jLayeredPane3.add(jTextFieldOutro1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jComboBoxSexo2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBoxSexo2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Masculino", "Feminino", " " }));
        jComboBoxSexo2.setBounds(450, 150, 100, 30);
        jLayeredPane3.add(jComboBoxSexo2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jSeparator2.setBounds(0, 120, 730, 20);
        jLayeredPane3.add(jSeparator2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTextFieldOutro3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldOutro3.setBounds(350, 320, 200, 30);
        jLayeredPane3.add(jTextFieldOutro3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jComboBoxSexo3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBoxSexo3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Masculino", "Feminino", " " }));
        jComboBoxSexo3.setBounds(450, 270, 100, 30);
        jLayeredPane3.add(jComboBoxSexo3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTextFieldExaminador3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldExaminador3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldExaminador3ActionPerformed(evt);
            }
        });
        jTextFieldExaminador3.setBounds(200, 270, 240, 30);
        jLayeredPane3.add(jTextFieldExaminador3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel23.setText("Outro:");
        jLabel23.setBounds(350, 300, 70, 20);
        jLayeredPane3.add(jLabel23, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel25.setText("Categoria:");
        jLabel25.setBounds(200, 300, 70, 20);
        jLayeredPane3.add(jLabel25, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jComboBoxCategoria3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBoxCategoria3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Professor Titular", "Professor Associado", "Professor Adjunto", "Outro", " " }));
        jComboBoxCategoria3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCategoria3ActionPerformed(evt);
            }
        });
        jComboBoxCategoria3.setBounds(200, 320, 140, 30);
        jLayeredPane3.add(jComboBoxCategoria3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel26.setText("Examinador:");
        jLabel26.setBounds(200, 250, 90, 17);
        jLayeredPane3.add(jLabel26, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel27.setText("Sexo:");
        jLabel27.setBounds(450, 250, 50, 17);
        jLayeredPane3.add(jLabel27, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 735, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
        );

        jTabbedPane5.addTab("Banca Examinador", jPanel2);

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel21.setText("Nome:");
        jLabel21.setBounds(20, 90, 41, 17);
        jLayeredPane4.add(jLabel21, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel22.setText("Sexo:");
        jLabel22.setBounds(270, 90, 36, 17);
        jLayeredPane4.add(jLabel22, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTextFieldNome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldNome.setBounds(20, 110, 240, 30);
        jLayeredPane4.add(jTextFieldNome, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jComboBoxSexo4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBoxSexo4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Masculino", "Feminino", " " }));
        jComboBoxSexo4.setBounds(270, 110, 100, 30);
        jLayeredPane4.add(jComboBoxSexo4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        tCandidatos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tCandidatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Candidatos:"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tCandidatos);
        tCandidatos.getColumnModel().getColumn(0).setResizable(false);

        jScrollPane1.setBounds(390, 80, 340, 190);
        jLayeredPane4.add(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButtonExcluir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icones/excluir.png"))); // NOI18N
        jButtonExcluir.setMnemonic('x');
        jButtonExcluir.setText("Excluir");
        jButtonExcluir.setBounds(250, 200, 120, 33);
        jLayeredPane4.add(jButtonExcluir, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButtonEditar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icones/edt.png"))); // NOI18N
        jButtonEditar.setMnemonic('e');
        jButtonEditar.setText("Editar");
        jButtonEditar.setBounds(130, 200, 120, 33);
        jLayeredPane4.add(jButtonEditar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButtonAdicionar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonAdicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icones/add.png"))); // NOI18N
        jButtonAdicionar.setMnemonic('a');
        jButtonAdicionar.setText("Adicionar");
        jButtonAdicionar.setBounds(10, 200, 120, 33);
        jLayeredPane4.add(jButtonAdicionar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel24.setText("Data de Nascimento:");
        jLabel24.setBounds(20, 140, 140, 17);
        jLayeredPane4.add(jLabel24, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jSeparator3.setBounds(0, 300, 730, 10);
        jLayeredPane4.add(jSeparator3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator4.setBounds(380, 50, 10, 250);
        jLayeredPane4.add(jSeparator4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jSeparator5.setBounds(0, 50, 730, 10);
        jLayeredPane4.add(jSeparator5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDateChooser1.setBounds(20, 160, 150, 30);
        jLayeredPane4.add(jDateChooser1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLayeredPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 734, Short.MAX_VALUE)
                .addGap(1, 1, 1))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
        );

        jTabbedPane5.addTab("Candidatos", jPanel3);

        jCheckBoxProvaEscrita.setText("Prova Escrita");

        jCheckBoxProvaDeTitulos.setText("Prova de Titulos");

        jCheckBoxProvaMemorial.setText("Prova Memorial");

        jCheckBoxProvaDidatica.setText("Prova Didática");
        jCheckBoxProvaDidatica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxProvaDidaticaActionPerformed(evt);
            }
        });

        jLabel3.setText("Selecione os tipos de provas que fazem parte desse concurso.");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(194, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBoxProvaDeTitulos)
                            .addComponent(jCheckBoxProvaMemorial)
                            .addComponent(jCheckBoxProvaDidatica)
                            .addComponent(jCheckBoxProvaEscrita))))
                .addGap(184, 184, 184))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jCheckBoxProvaEscrita)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBoxProvaDeTitulos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBoxProvaMemorial)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBoxProvaDidatica)
                .addContainerGap(126, Short.MAX_VALUE))
        );

        jTabbedPane5.addTab("Provas do Concurso", jPanel4);

        jTabbedPane5.setBounds(0, 50, 740, 380);
        jLayeredPane1.add(jTabbedPane5, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 738, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 498, Short.MAX_VALUE)
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-756)/2, (screenSize.height-545)/2, 756, 545);
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxClasseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxClasseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxClasseActionPerformed

    private void jTextFieldPresidenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPresidenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPresidenteActionPerformed

    private void jComboBoxCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxCategoriaActionPerformed

    private void jTextFieldExaminador1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldExaminador1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldExaminador1ActionPerformed

    private void jComboBoxCategoria1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCategoria1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxCategoria1ActionPerformed

    private void jButtonProximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProximoActionPerformed

        // TODO add your handling code here:
        int nextTab = jTabbedPane5.getSelectedIndex() + 1;
        if (nextTab < jTabbedPane5.getTabCount()) {
            jTabbedPane5.setSelectedIndex(nextTab);
        }

    }//GEN-LAST:event_jButtonProximoActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarActionPerformed
        // TODO add your handling code here:
        int nextTab = jTabbedPane5.getSelectedIndex() - 1;
        if (nextTab >= 0) {
            jTabbedPane5.setSelectedIndex(nextTab);
        }
    }//GEN-LAST:event_jButtonVoltarActionPerformed

    private void jCheckBoxProvaDidaticaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxProvaDidaticaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxProvaDidaticaActionPerformed

    private void jTextFieldExaminador3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldExaminador3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldExaminador3ActionPerformed

    private void jComboBoxCategoria3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCategoria3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxCategoria3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(janNovoConc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(janNovoConc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(janNovoConc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(janNovoConc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new janNovoConc().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel campus;
    private javax.swing.JLabel classe;
    private javax.swing.JLabel data;
    private javax.swing.JLabel edital;
    private javax.swing.JLabel instituicao;
    private javax.swing.JButton jButtonAdicionar;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonProximo;
    private javax.swing.JButton jButtonVoltar;
    private javax.swing.JCheckBox jCheckBoxProvaDeTitulos;
    private javax.swing.JCheckBox jCheckBoxProvaDidatica;
    private javax.swing.JCheckBox jCheckBoxProvaEscrita;
    private javax.swing.JCheckBox jCheckBoxProvaMemorial;
    private javax.swing.JComboBox jComboBoxCategoria;
    private javax.swing.JComboBox jComboBoxCategoria1;
    private javax.swing.JComboBox jComboBoxCategoria3;
    private javax.swing.JComboBox jComboBoxClasse;
    private javax.swing.JComboBox jComboBoxSexo;
    private javax.swing.JComboBox jComboBoxSexo2;
    private javax.swing.JComboBox jComboBoxSexo3;
    private javax.swing.JComboBox jComboBoxSexo4;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooserData;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JLayeredPane jLayeredPane3;
    private javax.swing.JLayeredPane jLayeredPane4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTabbedPane jTabbedPane5;
    private javax.swing.JTextField jTextFieldArea;
    private javax.swing.JTextField jTextFieldCampus;
    private javax.swing.JTextField jTextFieldEdital;
    private javax.swing.JTextField jTextFieldExaminador1;
    private javax.swing.JTextField jTextFieldExaminador3;
    private javax.swing.JTextField jTextFieldInstituicao;
    private javax.swing.JTextField jTextFieldMinisterio;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldOutro;
    private javax.swing.JTextField jTextFieldOutro1;
    private javax.swing.JTextField jTextFieldOutro3;
    private javax.swing.JTextField jTextFieldPresidente;
    private javax.swing.JLabel ministerio;
    private javax.swing.JTable tCandidatos;
    // End of variables declaration//GEN-END:variables
}
