/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import br.com.jdbc.Database;
import javax.swing.JOptionPane;

/**
 *
 * @author thiago
 */
public class janSobre extends javax.swing.JFrame {

    /**
     * Creates new form Sobre
     */
    public janSobre() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botao_CriarBanco = new javax.swing.JButton();
        botao_PopularBase = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        botao_CriarBanco.setText("Criar Banco de Dados");
        botao_CriarBanco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_CriarBancoActionPerformed(evt);
            }
        });

        botao_PopularBase.setText("Popular Base de Dados");
        botao_PopularBase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_PopularBaseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(botao_CriarBanco)
                .addGap(46, 46, 46)
                .addComponent(botao_PopularBase)
                .addContainerGap(51, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(201, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botao_CriarBanco)
                    .addComponent(botao_PopularBase))
                .addGap(76, 76, 76))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botao_CriarBancoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_CriarBancoActionPerformed
        try {
            Database database = new Database();

            database.deletaBanco();
            database.criarBanco();
            database.criarTabelas();
            
            JOptionPane.showMessageDialog(this, "Banco Criado com sucesso!", null, JOptionPane.INFORMATION_MESSAGE);
       
        } catch (Exception exceptError) {
            // Logger.getLogger(janProvaEscrita.class.getName()).log(Level.SEVERE, null, exceptError);
            JOptionPane.showMessageDialog(this, "ERRO: Não foi Possível Criar o Banco de Dados! \n Verifique suas dependências [MySQL, etc].", null, JOptionPane.ERROR_MESSAGE);
            exceptError.printStackTrace();
        }
    }//GEN-LAST:event_botao_CriarBancoActionPerformed

    private void botao_PopularBaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_PopularBaseActionPerformed
        try {
            
            Database database = new Database();
            database.populate();
            
            JOptionPane.showMessageDialog(this, "Banco Populado com sucesso! \n [ou não kkkkk]", null, JOptionPane.INFORMATION_MESSAGE);
       
        } catch (Exception exceptError) {
            // Logger.getLogger(janProvaEscrita.class.getName()).log(Level.SEVERE, null, exceptError);
            JOptionPane.showMessageDialog(this, "ERRO: Não foi Possível Popular o Banco de Dados! \n Verifique se o DB já Existe.", null, JOptionPane.ERROR_MESSAGE);
            exceptError.printStackTrace();
        }
    }//GEN-LAST:event_botao_PopularBaseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(janSobre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(janSobre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(janSobre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(janSobre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new janSobre().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botao_CriarBanco;
    private javax.swing.JButton botao_PopularBase;
    // End of variables declaration//GEN-END:variables
}
